class Glomeris < Formula
  desc "Evidence-first, policy-constrained developer storage autopilot for macOS"
  homepage "https://github.com/Chisanan232/glomeris"
  license "Apache-2.0"

  # No explicit `version` stanza: `brew audit --strict` rejects it as redundant
  # with the version Homebrew scans out of the release URL below.
  on_macos do
    on_arm do
      url "https://github.com/Chisanan232/glomeris/releases/download/v0.2.0/glomeris-aarch64-apple-darwin.tar.xz"
      sha256 "4eb08c3d2d38b2755d57ab40976c2e2983048b77252cbd159c48534c7c9ef375"
    end
    on_intel do
      url "https://github.com/Chisanan232/glomeris/releases/download/v0.2.0/glomeris-x86_64-apple-darwin.tar.xz"
      sha256 "bbbe87c68545189a200727de9a3da2d1c09db522f36ee89f164ca71b09026417"
    end
  end

  def install
    bin.install "glomeris"
  end

  test do
    # v0.2.0 has no `--version` flag; run with no arguments, which prints the
    # version banner and exits 0. Later releases add `--version` and this
    # formula is regenerated by cargo-dist at release time.
    assert_match version.to_s, shell_output(bin/"glomeris")
  end
end
